<h1>Категории</h1>
<a href="/admin/category/add/">Добавить категорию</a>
<br><br>
<?php
//здесь перехватываем сообщения из флэшмессенджера из addAction'a CategoryController'a
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('
        <div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
        </button>
        <ul>
        <li>')->setMessageSeparatorString('</li></li>')->setMessageCloseString('<li><ul></div>');

//если было сообщение соответ.типа, то оно будет выведено
echo $flash->render('error', ['alert', 'alert-dismissable', 'alert-danger']);
echo $flash->render('info', ['alert', 'alert-dismissable', 'alert-info']);
echo $flash->render('default', ['alert', 'alert-dismissable', 'alert-warning']);
echo $flash->render('success', ['alert', 'alert-dismissable', 'alert-success']);

?>

<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <th>#</th>
        <th>Ключ</th>
        <th>Название</th>
        <th>Действие</th>
    </tr>

    <?php
    foreach ($rowsWithResult as $category) {
        echo '<tr>
                  <td>' . $category->getId() . '</td>
                  <td>' . $category->getCategoryKey() . '</td>
                  <td>' . $category->getCategoryName() . '</td>
                  <td>
                  
                  <!-- $this это кто???
                  
                  
                  <!-- тут создаем ссылку admin/category/[:action/][:id/] , где заполняем :action на edit, и :id -->
                       <a href="' . $this->url('admin/category', array('action' => 'edit', 'id' => $category->getId())) . '">Редактировать</a>
                       &nbsp;&nbsp;<!--неравзрывный пробел (то есть две наши ссылкы будут через 2 пробела но обязательно на одной строке
                  <!-- тут создаем ссылку admin/category/[:action/][:id/] , где заполняем :action на delete, и :id -->
                  <!-- при клике на ссылку будет окно подтверждения, если да - то перейдем по ссылке, если нет - то стоим  -->
                       <a href="' . $this->url('admin/category', array('action' => 'delete', 'id' => $category->getId())) . '" onclick="if (confirm(\'Удалить запись?\')) ( document.location=this.href; ) return false;"> Удалить</a>
                  </td>
             </tr>';
    }
    ?>

    </tbody>
</table>